### ISSUE TITLE
Python Formatter breaks multiline strings

### ISSUE THREAD

**Issue by hjacobs** [WoLpH/python-formatter#2]
Triple-quotes for multiline strings (usually used as docstrings) get replaced with single quotes --- this obviously breaks the syntax.

Error is:
```
Unable to format 'myfile.py'
Traceback (most recent call last):
  File "/usr/local/bin/python-formatter", line 9, in <module>
    load_entry_point('formatter2==1.1.0', 'console_scripts', 'python-formatter')()
  File "/usr/local/lib/python2.7/dist-packages/formatter2/main.py", line 32, in main
    formatter.format_path(file_, args.recursive)
  File "/usr/local/lib/python2.7/dist-packages/formatter2/formatter.py", line 47, in format_path
    self.format_file(path)
  File "/usr/local/lib/python2.7/dist-packages/formatter2/formatter.py", line 59, in format_file
    code = self(name)
  File "/usr/local/lib/python2.7/dist-packages/formatter2/formatter.py", line 37, in __call__
    compile(formatted, '', 'exec')
  File "", line 35
    '
    ^
SyntaxError: EOL while scanning string literal

**Comment by WoLpH** [comment]
Can you show me the test code? I've tried this and it works just fine:
**myfile.py**
```
'''
Testing some 'triple-single' "quoted" stuff with quotes
'''

"""
Testing some 'triple-single' "quoted" stuff with quotes
"""
```

Running the test:
```
# python-formatter -vv myfile.py
offset: <TokenOffset[0x10c344910:STRING]'\'\'\'\nTesting some \'triple-single\' "quoted" stuff with quotes\n\'\'\'' (0,0) None>
offset: <TokenOffset[0x10bb26950:NEWLINE]'\n' (0,0) None>
offset: <TokenOffset[0x10c344a90:NL]'\n' (0,0) None>
offset: <TokenOffset[0x10c344ad0:STRING]'"""\nTesting some \'triple-single\' "quoted" stuff with quotes\n"""' (0,0) None>
offset: <TokenOffset[0x10bb26950:NEWLINE]'\n' (0,0) None>
offset: <TokenOffset[0x10c344a90:NL]'\n' (0,0) None>
offset: <TokenOffset[0x10c344a90:NL]'\n' (0,0) None>
offset: <TokenOffset[0x10c344b10:ENDMARKER]'' (0,0) None>
```

**Comment by hjacobs** [comment]
Just try:

```bash
$ sudo pip3 install formatter2
$ git clone https://github.com/zalando/connexion.git
$ python-formatter connexion/connexion/app.py
Unable to format 'connexion/connexion/app.py'
Traceback (most recent call last):
  File "/usr/local/bin/python-formatter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/formatter2/main.py", line 32, in main
    formatter.format_path(file_, args.recursive)
  File "/usr/local/lib/python3.4/dist-packages/formatter2/formatter.py", line 47, in format_path
    self.format_file(path)
  File "/usr/local/lib/python3.4/dist-packages/formatter2/formatter.py", line 59, in format_file
    code = self(name)
  File "/usr/local/lib/python3.4/dist-packages/formatter2/formatter.py", line 37, in __call__
    compile(formatted, '', 'exec')
  File "", line 1
    '
    ^
SyntaxError: EOL while scanning string literal
```

**Comment by WoLpH** [comment]
Indeed, apparently it doesn't work with multiline comments. I'll work on a fix :)

**Comment by hjacobs** [comment]
:+1: thanks :smile:

**Comment by WoLpH** [comment]
Well, that part has been fixed but I've found a new problem. Ternary if statements are still a problem.

**Comment by WoLpH** [comment]
Both issues are fixed now :)
